version: '3.7'

services:
  database:
    image: neo4j
    container_name: database
    environment:
       NEO4J_AUTH: neo4j/student
       ORG_NEO4J_DRIVER_URI: bolt://database:7687
    ports:
      - 7687:7687
      - 7474:7474

  springapi:
    image: correct-address
    links:
      - database
    ports:
      - 8091:8080
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:neo4j://database:7687/neo4j
      SPRING_DATASOURCE_USERNAME: neo4j
      SPRING_DATASOURCE_PASSWORD: student
      SPRING_DATASOURCE_URI : bolt://localhost:7687
    depends_on:
      - database
