version: "3"
services:
  neo4j:
    image: neo4j:4.0.2
    environment:
        NEO4J_AUTH: neo4j/student
        NEO4J_kafka_bootstrap_servers: kafka:19092
        NEO4J_dbms_logs_debug_level: DEBUG
    ports:
        - 7687:7687
    depends_on:
      - kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "12181:12181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 12181
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092
  docker-springboot-example:
      image: amiridokerid/docker-springboot-example:latest
      ports:
        - 8091:8091
      restart: unless-stopped
      build:
        context: ./
        dockerfile: Dockerfile
      depends_on:
        - neo4j
